#spring:
#  profiles:
#    include: real-db
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

spring:
  config:
    import: application-real-db.yml
