## 블로그 헤더 정보 설정, 상세 정보들은 feed에서 가져옴.
## title은 해당 파일에서 개발자가 구분하기 위함이며, 실제 데이터로 사용되지는 않음.
blogs:
  list:
    -
      url: https://jojoldu.tistory.com/
      rssUrl: https://jojoldu.tistory.com/rss
      title: 기억보단 기록을
    -
      url: https://woowabros.github.io/
      rssUrl: https://woowabros.github.io/feed.xml
      title: 우아한 형제들
    -
      url: https://brunch.co.kr/@javajigi/
      rssUrl: https://brunch.co.kr/rss/@@5tdm
      title: 박재성
    -
      url: https://johngrib.github.io/
      rssUrl: https://johngrib.github.io/feed.xml
      title: 기계인간
    -
      url: https://taetaetae.github.io/
      rssUrl: https://taetaetae.github.io/index.xml
      title: 꿈꾸는 태태태의 공간
    -
      url: https://velog.io/@kwonh/
      rssUrl: https://v2.velog.io/rss/@kwonh
      title: 권준혁
    -
      url: https://velog.io/@monkeydugi/
      rssUrl: https://v2.velog.io/rss/@monkeydugi
      title: monkeydugi
    -
      url: https://medium.com/daangn
      rssUrl: https://medium.com/feed/daangn
      title: 당근마켓
