#spring:
#  profiles:
#    include: real-db
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

spring:
  config:
#    activate:
#      on-profile: real
    import: real-db
